version: "3"
services:
  xmly1:
    image: q123458384/xmly_speed:latest
    ## driver: "json-file"
    restart: always
    container_name: xmly1
    environment:
      ## 填入cookie信息 ，多账号换行,或者创建多个容器
      - XMLY_SPEED_COOKIE=
      ## 通知服务
      - BARK=
      - SCKEY=
      - TG_BOT_TOKEN=
      - TG_USER_ID=
  xmly2:
    image: q123458384/xmly_speed:latest
    ## driver: "json-file"
    restart: always
    container_name: xmly2
    environment:
      ## 填入cookie信息 ，多账号换行
      - XMLY_SPEED_COOKIE=
      ## 通知服务
      - BARK=
      - SCKEY=
      - TG_BOT_TOKEN=
      - TG_USER_ID=
