name: Build Image
on:
  #防止fork乱用action设置只能手动触发构建
  workflow_dispatch:
jobs:
  build:
      runs-on: ubuntu-latest
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            with:
              publish: true
              imageName: q123458384/xmly_speed # dockerid/imageName
              platform: linux/arm64,linux/amd64 # 你准备构建的镜像平台
              tag: v1.0,latest # 默认latest，可以针对平台，修改tag
              dockerHubUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
              dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword
